export const PROJECT_EVALUATION_STATUS = {
  DRAFT: 'draft',
  NEEDS_EVALUATION: 'needs_evaluation',
  PARTIALLY_COMPLETED: 'partially_completed',
  COMPLETED: 'completed',
  FAILED: 'failed',
} as const;

export const PROJECT_EVALUATION_STATUS_LABEL = {
  [PROJECT_EVALUATION_STATUS.DRAFT]: 'Bản nháp',
  [PROJECT_EVALUATION_STATUS.NEEDS_EVALUATION]: 'Cần đánh giá',
  [PROJECT_EVALUATION_STATUS.PARTIALLY_COMPLETED]: 'Hoàn thành 1 phần',
  [PROJECT_EVALUATION_STATUS.COMPLETED]: 'Hoàn thành',
  [PROJECT_EVALUATION_STATUS.FAILED]: 'Không đạt',
} as const;

export const PROJECT_EVALUATION_STATUS_COLOR = {
  [PROJECT_EVALUATION_STATUS.DRAFT]: '#8c8c8c',
  [PROJECT_EVALUATION_STATUS.NEEDS_EVALUATION]: '#faad14',
  [PROJECT_EVALUATION_STATUS.PARTIALLY_COMPLETED]: '#1890ff',
  [PROJECT_EVALUATION_STATUS.COMPLETED]: '#52c41a',
  [PROJECT_EVALUATION_STATUS.FAILED]: '#ff4d4f',
} as const;

export enum MediaType {
  IMAGE = 'image',
  VIDEO = 'video',
}
